services:
  nginx:
    build:
      context: . #Root du projet
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - camagru-network

  api:
    build:
      dockerfile: back/Dockerfile
    networks:
      - camagru-network
    env_file: # Va ajouter les variables d'environnement du .env dans l'env du container.
      - ./back/.env

networks:
  camagru-network:
    driver: bridge
